### ISSUE TITLE
Suggestion: Update README to include OS compatibility.

### ISSUE THREAD

**Issue by PureKrome** [SimonCropp/LocalDb#15]
I found this out the hardway :) 

Azure DevOps + Ubuntu image == 💥 . Initially it was this:

```
-------- System.TypeInitializationException : The type initializer for 'LocalDbApi' threw an exception.
------------ System.PlatformNotSupportedException : Registry is not supported on this platform.
```

because Ubuntu doesn't have a registry (of course!).

Further research indicated that Sql Server Express _does_ exist for Linux (which I thought it did ....) but does **not** have `LocalDB` support provided (which I didn't know).

As such, suggestion is to have a note/notice/reminder about how this library uses LocalDB (obviously) butonly works only on Windows OS.

**Comment by PureKrome** [comment]
Another thought came to mind after posting this. What are the options for people working on Mac OSX / Linux ? There are no options _with_ LocalDB?

**Comment by SimonCropp** [comment]
i can add a sqlexpress mode

**Comment by PureKrome** [comment]
> i can add a sqlexpress mode

That might be ... interesting :) It might not be as performant as LocalDB because of the startup steps? But still an option for non-windows peeps?

**Comment by SimonCropp** [comment]
i think the perf should be equivalent. either way it is spinning up a sql instance

**Comment by PureKrome** [comment]
Awesome :) what are your thoughts? worth it?

also, what would be the scenario for using an exisiting _seeded_ db, if someone wanted to use that (instead of creating the tables, inserting data, etc)

**Comment by SimonCropp** [comment]
> Awesome :) what are your thoughts? worth it?

For me, no. i currently dont need it. for others? hard to tell

> also, what would be the scenario for using an exisiting seeded db, if someone wanted to use that (instead of creating the tables, inserting data, etc)

there would need to be a convention for the template db. eg prefixed with the name of the sqlinstance

in the short teerm, i am happy to accept a PR about "only works on windows"
