### ISSUE TITLE
Directory cleanup of LocalDB instance folder not working properly

### ISSUE THREAD

**Issue by coder-5943123** [SimonCropp/LocalDb#411]
Hi,

Thank you for a great library.

I'm using xUnit for running unittests, after running tests in a test class I call the SqlInstance.Cleanup() method, which successfully stops and deletes the running Localdb instance.

There is a problem with some files not being deleted in the instance folder.

Before cleanup while running the tests:
![image](https://user-images.githubusercontent.com/45265821/141273635-6a647bd8-77ee-4ffd-91a0-8b519d9654dc.png)

After the cleanup:
![image](https://user-images.githubusercontent.com/45265821/141273744-5d69dcb0-bb02-480e-9b31-dd6266f76702.png)

**Comment by SimonCropp** [comment]
you should not be cleaning up those files. Localdb will handle that for you

**Comment by coder-5943123** [comment]
But the files in the second image is still left in the instance folder, running unit tests a second time creates more files:
![image](https://user-images.githubusercontent.com/45265821/141286601-df0b7446-ed64-41dd-8215-29f56127e003.png)

Each time I run the unit tests .log .xel .trc files are created in the instance folder. So the SqlInstance.Cleanup() method is only removing .mdf and .ldf files.

**Comment by SimonCropp** [comment]
can u share a unit test that causes those

**Comment by SimonCropp** [comment]
can u try 10.8.1

**Comment by coder-5943123** [comment]
Thx for trying to fix this issue, but updating to 10.8.1 didn't help. The files are still in the localdb instance folder, i recreated the issue in a small demo project.

https://github.com/coder-5943123/localdb-test-project-issue-411

The remaining files are found in this location
C:\Users\yourusername\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\LocalDbUnitTestInstance

**Comment by SimonCropp** [comment]
can you have a go at submitting a pull request that fixes this
