### ISSUE TITLE
execute await using var db = await DbInstance.Default.FundationDb() twice error

### ISSUE THREAD

**Issue by zhaoqinghai** [SimonCropp/LocalDb#438]
![image](https://user-images.githubusercontent.com/26404526/226493440-6c3c1220-5125-4653-b743-1046b84078ed.png)

**Comment by zhaoqinghai** [comment]
public class DbInstance
    {
        static SqlInstance<LocalDbContext> sqlInstance;

        static DbInstance() =>
            sqlInstance = new SqlInstance<LocalDbContext>(
                builder => new (builder.Options),
                storage: new Storage("LocalDb", "E:\\LocalCache"),
                sqlOptionsBuilder: builder =>
                {
                    builder.EnableRetryOnFailure(5);
                    builder.CommandTimeout(5);
                });

        public static DbInstance Default = new Lazy<DbInstance>().Value;

        public Task<SqlDatabase<LocalDbContext>> FundationDb()
        {
            return sqlInstance.Build();
        }
    }

**Comment by SimonCropp** [comment]
can u submit a failing unit test as a pull request

**Comment by zhaoqinghai** [comment]
#440
